import * as React from "react";
import { createTheme } from "@mui/material/styles";
import Head from "next/head";
import LoginView from "@/src/views/Login";

// TODO remove, this demo shouldn't need to reset the theme.
const defaultTheme = createTheme();

export default function Login() {
  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="logo" />
      </Head>
      <LoginView />
    </>
  );
}
